spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/RecapSpring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
server:
  port: 8081